project: default
source:
  repoURL: https://github.com/Roelandict/Semster-3-pico-cluster.git
  path: Remote/glpi
  targetRevision: HEAD
  directory:
      recurse: true
destination:
  server: https://kubernetes.default.svc
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
