apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Roelandict/Semster-3-pico-cluster.git'
    targetRevision: HEAD
    path: Remote/authentik
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true