apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt server adres
    server: https://acme-v02.api.letsencrypt.org/directory
    # Jouw e-mailadres voor meldingen over verlopen
    email: roelandict@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
